---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd"
stores:
  yaml:
    indent: 2
