apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:MM9bJ+ZkisOduP4ZbrZceF9QXz6ybowY5a+d0VytIIZ9lmKXDGcj6w==,iv:nwSJBkOpnW5VEu8sVigKyifXwCvUaR4jbfO9klxpabc=,tag:Xmh59sGDRNfdJjV2ddx9lw==,type:str]
sops:
  age:
    - recipient: age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U2FISStoTDRhYjM1ci9m
        SzZ4VEhvenZrN0V3TlN4RFlvUHVMVFFWaGc4CkxiNUE5TCtETjZnaGE1OTNvTjhT
        WmZkNDhmMXZTMTBCMUNVSS9McUNJNDQKLS0tIExoTCtEaWthUTNnZERwSG9Dclpr
        ZWo0dnB5Yjg4V25POTlFYjZUZ0NpV0UKk8mAh8GScYT7h+5Lt7R3JNAbG8uxemfd
        aeI68ZRzAL8jgfRi8vm5eA9kQjsNXgwuIjJTDhYW10PA3VM7CnSpWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T22:42:33Z"
  mac: ENC[AES256_GCM,data:WPpCFf9P+rBJuFYSK8DOvhf4vsl1G5ghCsznx4WyFyoBKESLHO+p8qTGDOhAqU2Fn9kv2c1s77XzEY56RrQIdDquDwwpiBWOC7cNkYYYZ/nqhJ3MxR2UmAQ2sEqWxlXGFVQ/s3/mGsbmSJ+i1BZ2YoOD4VTdaCP6Fvuzu43yFB8=,iv:InZ4qiVJBMR7j5SYaTigOi/Q+m4RA2aCr1d4a15Eq1g=,tag:mFfPBCqw+QR6b+AUSvEYIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
