all:
  vars:
    control_plane_endpoint: 10.1.10.235
    load_balancer_ip_pool:
      - 10.1.10.231/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.1.10.240, mac: 'e4:54:e8:6e:de:08', disk: nvme0n1, network_interface: eno2}
        metal1: {ansible_host: 10.1.10.245, mac: 'e4:54:e8:6f:2c:cd', disk: nvme0n1, network_interface: eno2}
        metal2: {ansible_host: 10.1.10.250, mac: '00:23:24:cb:b5:69', disk: nvme0n1, network_interface: eno1}
          #    workers:
          #      hosts:
          #  metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
