apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Kk0KFM5KQo8B9AEOQP9P9WrW,iv:uGeq0NIn987mKzwQOLXLhY+4AnW43IRC58/cqmUT4OQ=,tag:Us0wP97vg6U5ZAoDzKmckg==,type:str]
sops:
  age:
    - recipient: age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdjIxVENiaDZPcVhrcTFm
        SzcxS040N2ZuUm5UQzVYMnFRZ0NGeVg0S3lJCi9lRHRncWYvaW82dGh3ZzRoTURH
        YWtCMFN5TDhRTXB0L3ZQQWg2aXBGU0EKLS0tIHhsYm9udEc1Vk5OQ1g4NTdoZTFr
        RjhCeERTU0JveWJDWnNHRnBGM3ZBbkkKc27cuhWZI3YN60tYE6dqTX+jPsGByclB
        HiDAr+IEiTnbkI17VOZAzTUn4eSTpAkj1NfvH+/swDYnkMULMPNu6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T22:42:33Z"
  mac: ENC[AES256_GCM,data:n0KrGa1hf+q7lR5W+4mBwUFzvz3iQJbtRayMW6j0rDQ/3n5sl2PgY7qQIiL0348O4QWKf9s2uR7zhIYTrIr3NARBvl4xRaRM0A4xZ5mYtyNAnIvsRPoLo/4LFcKJteHIr2e6Ah/IRyo/bwmqF9MudgcgcleS2fLyJsWucqbUEyY=,iv:fv2w/yCgXFCoRkX2WWoWRsFxj9tRqW8opF/hcdshyCs=,tag:ZOq7IrOA3467/FXfkafILA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
