apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XuLLziGFwMzuAquHsikKF0yT,iv:WpP0CjeIf4PBxtQL6BRQPbUlEcOzITJ6IWx7DuFj7EQ=,tag:wcqEEhdMjtl6MhsNIjzP4A==,type:str]
sops:
  age:
    - recipient: age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM2tGMnI0Wkc3ekVLS3FR
        TGs2RlQxN0IzQy80N3Eyb0ZTWXZRcWUydFRNCms1SVV3RjhzYzNRR25oUTdhU3Iy
        em1xbjE3MGJWaUoyMGhINHZ3VlRVQ1kKLS0tIDhOaW1OZ0traWM1WGdpaFZKYVhF
        cGpkTEFLeUc3UE1JZnh0VGpQSjlOY2MKt1MTElQ9KEU90cXAoMb1pUS6TADEbpOA
        ACkI5AiiwlnycQjf1wZLisdxEAq6KBbgQ5PcJB1JJwCCKiVPG5Y36Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T22:47:54Z"
  mac: ENC[AES256_GCM,data:U4irrLlsLzBHaGOtj9771Ke+4MyvKn88W7DTm9SzrGw0gHl4FWjQp7CIMNaSD7rYhFerNescxRN2rp2V/FF5xYHD9f2KlrNUVdx/YAfXhHdzxkx3fgvZK5lX7a1c4stBoiEDqbA8eb0mcAlPL+iM0eaMtSpk4hSoYPo1RRU7V/o=,iv:gQgPlivoRqToQsKsEu+vfTPydsw5VdN5WnHbONz7Mww=,tag:T8siIaocmJVctM3HwVON1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
