apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zAlRGMBWTb/tQqqQaYd3kS0PjyheWX24Mls7nOmJEK4=,iv:vBXxFzH4mXHZQWWuSAVitmDsY7p+tjdclwU82HBh/7M=,tag:2RGa3LGSAIoRq0qfAap58A==,type:str]
sops:
  age:
    - recipient: age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eG1sOXJYMGlYVmVRZEtO
        dGpzQk0vdnJkc1B6T2ZUUlJVQ01IVDlZc1ZFCnBXSkhwdThXVFFLZ3U5VU5WMHhU
        djZoOTZDcjl4YlFaQkh1U0QvTlA0YlUKLS0tIGI2OWhHb3YwRFZ0NFVNeUc4WlVC
        bmQ0OGkyMmtTNXJObFNaYXJubG11eWcKi87A0K8lfpKod8+m9B7aNSNtPnftyQd3
        5PgiNDGIfyojUaTS7WyzSN6VcnDjBybRajTMK8UbDY8YBf19eDHTJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T22:42:32Z"
  mac: ENC[AES256_GCM,data:IuypeN/dKzh0o7eFTdqk61itHiR4sp9IBdc5fD7u6bNd5xPq1f3JHVlzS5lNGefbZ+e2IufeePMsiWCa/ofuUIVxY4TxLmhb3m3xwjFRpAKbJuXNpUhSCp197jWOSI9Ei3Xs73mbOE3BcipsXO/tyOd5qhmdudROuIzFdDJgrPU=,iv:UO4//NsmgnQ8hgeIbYLZwchKY8xwvEJpMO1mTHvgDI8=,tag:2r9VHVAtibD/EHyQyFs2iQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
