apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:W88K1bPoYRGqso7p+FfkIOQaVvfQWgbzLWuEn/+0nKWBjm45uczodRO5cPQX3nqJUlcIWASRu53DB06ezD91nCOmiTchebJ6mD8FvFrQeTUE6E3YQ2l8YDoyH3cQaSGMDm7zMcwf05DZl4Xaz8DBpWAuKqC7v/bHinmJAuLcBlQ3m5oKfCS6DMMwbnPHWy1BXs3Rb9V1zIzwedcnD8J3wRS9vA3MWvsYgiRPOxxqYkfZPFly,iv:AVy1Z0mL72Is+tTK0DZ3hcAsTmCeEBw7EAHXK7uLhmQ=,tag:jC2GpsH0/hQLqGNkccvAuA==,type:str]
sops:
  age:
    - recipient: age1v907e6zge4a3aaq5tj4zvpl5cum8wh0atehmjcqau2unkyu0hpgssqv8cd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbk9jZGY2cEVrRDROeHZo
        S0J3WDh6dC9ZQ3JuUVJKbXZ0SkxyU251dkJjCkJ4ZEtJTlZsbnluZVU2NXJnaG5q
        d2p1NWZqdnUzb00vT01RaGd4NmYyZWsKLS0tIHIyc0dINXg1RElXZXFSMWNMcDRj
        VUthb1JxUC9QRTI2aVVmUFRPY0ZteEkKmKRyMjZbA0cOMfQTz2iS//2eWlh8yLo/
        K2rU02ukggqbpNVRTpp95XEScUqjKv2ykd5N+cjHinOwqdxaeYvSrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T22:42:33Z"
  mac: ENC[AES256_GCM,data:+idBMrveuqLNUGJqfiEsf98JtmDEXAyZjMT5haLdQglN8mQ4s+XCIrvd4TlN2cDJugkMci5mx/qNQGy8cQMlsaIwHdhMOQ+nJuLLvK3fJzTgAmvS0fbGo4V1wgKjXDjWpuuz41JWzx4bphnCyF37MFQPvGzcdmq25ygHP+82gEQ=,iv:+c4XvJERUZYplO8gqUJISy4fMAUe7VjBv0tgL04Donw=,tag:TULdwWqHpV/qUWDrGyoeSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
